services:
  - type: web
    name: todo-app-backend
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        from: secret
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
